- name: Configurar repositorio kubernetes
  blockinfile:
    path: /etc/yum.repos.d/kubernetes.repo
    create: yes
    block: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      exclude=kubelet kubeadm kubectl
  become: yes

- name: Instalar kubernetes
  dnf:
    name: "{{ rpm_k8s }}"
    state: present
    disable_excludes: 'kubernetes'
  become: yes

- name: Activar el servicio de kubernetes
  systemd:
    name: kubelet
    state: started
    enabled: yes
    masked: no
  become: yes